# Generated by Django 5.0.6 on 2024-06-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heartvital',
            name='HeartDisease',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='heartvital',
            name='prediction_probability',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='heartvital',
            name='ChestPainType',
            field=models.CharField(choices=[('TA', 'Typical Angina'), ('ATA', 'Atypical Angina'), ('NAP', 'Non-Anginal Pain'), ('ASY', 'Asymptomatic')], max_length=255, verbose_name='Chest Pain Type'),
        ),
        migrations.AlterField(
            model_name='heartvital',
            name='ExerciseAngina',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=255, verbose_name='Exercise Anginia'),
        ),
        migrations.AlterField(
            model_name='heartvital',
            name='FastingBS',
            field=models.CharField(choices=[('0', 'Less than or equal to 120'), ('1', 'More than to 120')], max_length=255, verbose_name='Fasting Blood Sugar (60-900)'),
        ),
        migrations.AlterField(
            model_name='heartvital',
            name='MaxHR',
            field=models.IntegerField(verbose_name='Maximum Heart Rate (60-220)'),
        ),
        migrations.AlterField(
            model_name='heartvital',
            name='Oldpeak',
            field=models.FloatField(verbose_name='Oldpeak (-2.5 - +2.5)'),
        ),
        migrations.AlterField(
            model_name='heartvital',
            name='RestingBP',
            field=models.IntegerField(verbose_name='Resting Blood Pressure (60-220)'),
        ),
        migrations.AlterField(
            model_name='heartvital',
            name='RestingECG',
            field=models.CharField(choices=[('Normal', 'Normal'), ('ST', 'having ST-T wave abnormality'), ('LVH', "showing probable or definite left ventricular hypertrophy by Estes' criteria")], max_length=255, verbose_name='Resting ECG Condtion'),
        ),
        migrations.AlterField(
            model_name='heartvital',
            name='ST_Slope',
            field=models.CharField(choices=[('Up', 'upsloping'), ('Flat', 'flat'), ('Down', 'downsloping')], max_length=255),
        ),
    ]
